config:
  send_anonymous_usage_stats: False

default:
  outputs:

    dev: # User-Password config
      type: snowflake
      account: ti85806.ap-south-1.aws
      user: KARANMALHOTRA
      password: Grass@89
      role: ACCOUNTADMIN
      database: DEV
      warehouse: COMPUTE_WH
      schema: DBT_KMALHOTRA
      threads: 1
      client_session_keep_alive: False

  target: dev
